---
- name: Import packagecloud gpg key
  become: yes
  apt_key:
    url: https://packagecloud.io/github/git-lfs/gpgkey
    state: present

- name: Ensure depdendencies are installed
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - debian-archive-keyring
      - apt-transport-https

- name: Setup apt repo configuration
  become: yes
  apt_repository:
    repo: "deb https://packagecloud.io/github/git-lfs/{{ansible_distribution|lower}}/ {{ansible_distribution_release}} main"
    state: present
    filename: "github_git-lfs.lfs"
    update_cache: yes
    mode: 0644

- name: Install Git LFS
  become: yes
  apt:
    name: git-lfs
    state: latest
  notify:
    - Invoke Git LFS install
